- type: department
  id: Cargo
  name: department-Cargo
  description: department-Cargo-description
  color: "#A46106"
  roles:
  - CargoTechnician
  - Quartermaster
  - SalvageSpecialist

- type: department
  id: Civilian
  name: department-Civilian
  description: department-Civilian-description
  color: "#a3a3a3"
  weight: -10
  roles:
  - Boxer
  - Chaplain
  - Clown
  - Mime
  - Musician
  - Reporter
  - Visitor
  - Zookeeper

- type: department
  id: CentralCommand
  name: department-CentralCommand
  description: department-CentralCommand-description
  color: "#007a0e"
  roles:
  - CentralCommandOfficial
  - NanotrasenRepresentative  # Goobstation
  - BlueshieldOfficer # Goobstation
  # these ones are disabled still -steve
  - CBURN
  - ERTLeader
  - ERTChaplain
  - ERTJanitor
  - ERTMedical
  - ERTSecurity
  - ERTEngineer
  - DeathSquad
  - HecuOperative
  editorHidden: false
  weight: 120

- type: department
  id: Command
  name: department-Command
  description: department-Command-description
  color: "#334E6D"
  roles:
#  - CentralCommandOfficial
  - Captain
  - ChiefEngineer
  - ChiefMedicalOfficer
  - HeadOfPersonnel
  - HeadOfSecurity
  - ResearchDirector
  - Quartermaster
#  - NanotrasenRepresentative # Goobstation
  # still quite disabled -steve
  - CBURN
  - ERTLeader
  - ERTChaplain
  - ERTJanitor
  - ERTMedical
  - ERTSecurity
  - ERTEngineer
  - DeathSquad
  - HecuOperative
  primary: false
  weight: 100

- type: department
  id: Engineering
  name: department-Engineering
  description: department-Engineering-description
  color: "#EFB341"
  roles:
  - AtmosphericTechnician
  - ChiefEngineer
  - StationEngineer
  - TechnicalAssistant

- type: department
  id: Medical
  name: department-Medical
  description: department-Medical-description
  color: "#52B4E9"
  roles:
  - Chemist
  - ChiefMedicalOfficer
  - MedicalDoctor
  - MedicalIntern
  - Psychologist
#  - Paramedic (entirely unneeded lmao)

- type: department
  id: Security
  name: department-Security
  description: department-Security-description
  color: "#DE3A3A"
  weight: 20
  roles:
  - HeadOfSecurity
  - SecurityCadet
  - SecurityOfficer
  - Detective
  - Warden
  - Maid

- type: department
  id: Science
  name: department-Science
  description: department-Science-description
  color: "#D381C9"
  roles:
  - ResearchDirector
  - Scientist
  - ResearchAssistant

- type: department
  id: Silicon
  name: department-Silicon
  description: department-Silicon-description
  color: "#D381C9"
  roles:
  - Borg
  - StationAi
  
- type: department
  id: Service
  name: department-Service
  description: department-Service-description
  color: "#9FED58"
  weight: 10
  roles:
  - HeadOfPersonnel
  - Botanist
  - Chef
  - Bartender
  - Janitor
  - Librarian
  - ServiceWorker
  - Lawyer

- type: department
  id: Assistance
  name: department-Assistance
  description: department-Assistance-description
  color: "#a18672"
  weight: 9
  roles:
  - ServiceWorker
  - SecurityCadet
  - ResearchAssistant
  - MedicalIntern
  - TechnicalAssistant
  - Passenger
 
